[package]
name = "styx-proto-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
styx-proto = { path = ".." }

[[bin]]
name = "decode_arbitrary"
path = "fuzz_targets/decode_arbitrary.rs"
test = false
doc = false

[[bin]]
name = "decode_encode_roundtrip"
path = "fuzz_targets/decode_encode_roundtrip.rs"
test = false
doc = false
