[package]
name = "styx-resolution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "styx resolution feature crate."

[dependencies]
styx-proto = { path = "../styx-proto" }
styx-core = { path = "../styx-core" }
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
styx-core = { path = "../styx-core", features = ["test-support"] }
hickory-proto.workspace = true
criterion.workspace = true
stats_alloc.workspace = true

[[bench]]
name = "pipeline"
harness = false

[lints]
workspace = true
