//! Upstream health tracking and observation fold.
//!
//! Provides the private fold over query outcomes that derives per-member SRTT,
//! failure count, and circuit breaker status.

use std::time::{Duration, Instant};

use styx_core::FailureClass;

use crate::domain::circuit::{CircuitConfig, CircuitState, FailureCount};

/// The recorded result of a single resolution attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// Query completed successfully with a usable response.
    Success {
        /// Round-trip time of the resolution.
        latency: Duration,
        /// Whether this observation was generated by a probe query.
        was_probe: bool,
    },
    /// Query failed to produce a valid answer.
    Failure {
        /// The classification of the failure.
        class: FailureClass,
        /// Whether this observation was generated by a probe query.
        was_probe: bool,
    },
}

impl Outcome {
    /// Returns the observed latency if this was a success.
    #[must_use]
    pub const fn latency(&self) -> Option<Duration> {
        match self {
            Self::Success { latency, .. } => Some(*latency),
            Self::Failure { .. } => None,
        }
    }

    /// Returns whether this outcome was triggered by an active probe.
    #[must_use]
    pub const fn was_probe(&self) -> bool {
        match self {
            Self::Success { was_probe, .. } | Self::Failure { was_probe, .. } => *was_probe,
        }
    }
}

/// Concrete health state tracked per pool member.
///
/// Private fold over resolution outcomes; never shared outside the pool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HealthState {
    srtt: Option<Duration>,
    consecutive_failures: FailureCount,
    circuit: CircuitState,
    last_probe_at: Option<Instant>,
    last_outcome_at: Option<Instant>,
    half_open_successes: u32,
}

impl Default for HealthState {
    fn default() -> Self {
        Self::new()
    }
}

impl HealthState {
    /// Creates a fresh, cold-start `HealthState`.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            srtt: None,
            consecutive_failures: FailureCount::zero(),
            circuit: CircuitState::Closed,
            last_probe_at: None,
            last_outcome_at: None,
            half_open_successes: 0,
        }
    }

    /// Returns the smoothed round-trip time EWMA, if at least one sample was recorded.
    #[must_use]
    pub const fn srtt(&self) -> Option<Duration> {
        self.srtt
    }

    /// Returns the current circuit breaker state.
    #[must_use]
    pub const fn circuit(&self) -> CircuitState {
        self.circuit
    }

    /// Returns the current consecutive failure count.
    #[must_use]
    pub const fn consecutive_failures(&self) -> FailureCount {
        self.consecutive_failures
    }

    /// Returns the timestamp of the last recorded outcome, if any.
    #[must_use]
    pub const fn last_outcome_at(&self) -> Option<Instant> {
        self.last_outcome_at
    }

    /// Returns the timestamp of the last probe execution, if any.
    #[must_use]
    pub const fn last_probe_at(&self) -> Option<Instant> {
        self.last_probe_at
    }

    /// Observes a new resolution outcome and advances the health state.
    pub fn observe(&mut self, outcome: Outcome, now: Instant, config: &CircuitConfig) {
        self.last_outcome_at = Some(now);
        if outcome.was_probe() {
            self.last_probe_at = Some(now);
        }

        match outcome {
            Outcome::Success { latency, .. } => self.record_success(latency, config),
            Outcome::Failure {
                class: FailureClass::AnswerFault,
                ..
            } => self.record_answer_fault(outcome.latency()),
            Outcome::Failure {
                class: FailureClass::UpstreamFault,
                ..
            } => self.record_upstream_fault(now, config),
        }
    }

    /// Determines whether this upstream is available for dispatch.
    #[must_use]
    pub fn is_available(&self, now: Instant, config: &CircuitConfig) -> bool {
        match self.circuit {
            CircuitState::Closed => true,
            CircuitState::HalfOpen { in_flight } => !in_flight,
            CircuitState::Open { since } => {
                let elapsed = now.checked_duration_since(since).unwrap_or_default();
                elapsed >= config.open_cooldown
            }
        }
    }

    /// Attempts to admit a query or probe for dispatch, updating in-flight state.
    pub fn try_admit(&mut self, now: Instant, config: &CircuitConfig) -> bool {
        match self.circuit {
            CircuitState::Closed => true,
            CircuitState::HalfOpen { ref mut in_flight } => {
                if *in_flight {
                    false
                } else {
                    *in_flight = true;
                    true
                }
            }
            CircuitState::Open { since } => {
                let elapsed = now.checked_duration_since(since).unwrap_or_default();
                if elapsed >= config.open_cooldown {
                    self.circuit = CircuitState::HalfOpen { in_flight: true };
                    true
                } else {
                    false
                }
            }
        }
    }

    /// Attempts to admit a background health probe, transitioning Open to HalfOpen.
    pub fn try_admit_probe(&mut self) -> bool {
        match self.circuit {
            CircuitState::Closed => true,
            CircuitState::HalfOpen { ref mut in_flight } => {
                if *in_flight {
                    false
                } else {
                    *in_flight = true;
                    true
                }
            }
            CircuitState::Open { .. } => {
                self.circuit = CircuitState::HalfOpen { in_flight: true };
                true
            }
        }
    }

    /// Checks if the member has received no real or probe traffic within `window`.
    ///
    /// Cold-start members with no recorded outcomes return `true`.
    #[must_use]
    pub fn is_idle_beyond(&self, window: Duration, now: Instant) -> bool {
        let most_recent = match (self.last_outcome_at, self.last_probe_at) {
            (None, None) => return true,
            (Some(a), None) => a,
            (None, Some(b)) => b,
            (Some(a), Some(b)) => a.max(b),
        };

        let elapsed = now.checked_duration_since(most_recent).unwrap_or_default();
        elapsed >= window
    }

    /// Transitions an Open circuit to HalfOpen when starting a trial query or probe.
    pub fn mark_half_open(&mut self) {
        if let CircuitState::Open { .. } = self.circuit {
            self.circuit = CircuitState::HalfOpen { in_flight: false };
            self.half_open_successes = 0;
        }
    }

    fn record_success(&mut self, latency: Duration, config: &CircuitConfig) {
        self.srtt = Some(match self.srtt {
            None => latency,
            Some(existing) => compute_ewma(existing, latency),
        });
        self.consecutive_failures = FailureCount::zero();

        match self.circuit {
            CircuitState::Closed => {}
            CircuitState::HalfOpen { .. } => {
                self.half_open_successes = self.half_open_successes.saturating_add(1);
                if self.half_open_successes >= config.half_open_successes {
                    self.circuit = CircuitState::Closed;
                    self.half_open_successes = 0;
                } else {
                    self.circuit = CircuitState::HalfOpen { in_flight: false };
                }
            }
            CircuitState::Open { .. } => {
                self.circuit = CircuitState::Closed;
                self.half_open_successes = 0;
            }
        }
    }

    fn record_answer_fault(&mut self, latency: Option<Duration>) {
        if let Some(sample) = latency {
            self.srtt = Some(match self.srtt {
                None => sample,
                Some(existing) => compute_ewma(existing, sample),
            });
        }
        if let CircuitState::HalfOpen { ref mut in_flight } = self.circuit {
            *in_flight = false;
        }
    }

    fn record_upstream_fault(&mut self, now: Instant, config: &CircuitConfig) {
        self.consecutive_failures = self.consecutive_failures.increment_saturating();
        self.half_open_successes = 0;

        match self.circuit {
            CircuitState::Closed => {
                if self.consecutive_failures.value() >= config.failure_threshold {
                    self.circuit = CircuitState::Open { since: now };
                }
            }
            CircuitState::HalfOpen { .. } | CircuitState::Open { .. } => {
                self.circuit = CircuitState::Open { since: now };
            }
        }
    }
}

/// Computes EWMA with alpha = 1/8 using checked arithmetic.
///
/// `new_srtt = (7 * old + sample) / 8`
fn compute_ewma(old: Duration, sample: Duration) -> Duration {
    let old_nanos = old.as_nanos();
    let sample_nanos = sample.as_nanos();

    let updated_nanos = old_nanos
        .checked_mul(7)
        .and_then(|seven_old| seven_old.checked_add(sample_nanos))
        .and_then(|sum| sum.checked_shr(3))
        .unwrap_or(old_nanos);

    let nanos_u64 = u64::try_from(updated_nanos).unwrap_or(u64::MAX);
    Duration::from_nanos(nanos_u64)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cold_start_is_idle_and_available() {
        let health = HealthState::new();
        let config = CircuitConfig::default();
        let now = Instant::now();

        assert!(health.is_idle_beyond(Duration::from_secs(10), now));
        assert!(health.is_available(now, &config));
        assert_eq!(health.circuit(), CircuitState::Closed);
        assert_eq!(health.srtt(), None);
    }

    #[test]
    fn test_circuit_tripping_and_recovery() {
        let mut health = HealthState::new();
        let config = CircuitConfig {
            failure_threshold: 2,
            open_cooldown: Duration::from_secs(5),
            half_open_successes: 2,
        };
        let now = Instant::now();

        // 1st failure: remains closed
        health.observe(
            Outcome::Failure {
                class: FailureClass::UpstreamFault,
                was_probe: false,
            },
            now,
            &config,
        );
        assert_eq!(health.circuit(), CircuitState::Closed);
        assert!(health.is_available(now, &config));

        // 2nd failure: trips open
        health.observe(
            Outcome::Failure {
                class: FailureClass::UpstreamFault,
                was_probe: false,
            },
            now,
            &config,
        );
        assert_eq!(health.circuit(), CircuitState::Open { since: now });
        assert!(!health.is_available(now, &config));

        // Advance before cooldown: still unavailable
        let mid = now.checked_add(Duration::from_secs(2)).expect("advance");
        assert!(!health.is_available(mid, &config));

        // Advance past cooldown: becomes available for half-open trial
        let past = now.checked_add(Duration::from_secs(6)).expect("advance");
        assert!(health.is_available(past, &config));
        assert!(health.try_admit(past, &config));
        assert_eq!(health.circuit(), CircuitState::HalfOpen { in_flight: true });
        assert!(!health.try_admit(past, &config));

        // First success in HalfOpen (needs 2 for Closed)
        health.observe(
            Outcome::Success {
                latency: Duration::from_millis(20),
                was_probe: true,
            },
            past,
            &config,
        );
        assert_eq!(
            health.circuit(),
            CircuitState::HalfOpen { in_flight: false }
        );
        assert!(health.try_admit(past, &config));

        // Second success restores to Closed
        health.observe(
            Outcome::Success {
                latency: Duration::from_millis(20),
                was_probe: true,
            },
            past,
            &config,
        );
        assert_eq!(health.circuit(), CircuitState::Closed);
        assert!(health.is_available(past, &config));
    }

    #[test]
    fn test_half_open_failure_rearms_cooldown() {
        let config = CircuitConfig {
            failure_threshold: 2,
            open_cooldown: Duration::from_secs(5),
            half_open_successes: 1,
        };
        let now = Instant::now();
        let mut health = HealthState::new();

        health.observe(
            Outcome::Failure {
                class: FailureClass::UpstreamFault,
                was_probe: false,
            },
            now,
            &config,
        );
        health.observe(
            Outcome::Failure {
                class: FailureClass::UpstreamFault,
                was_probe: false,
            },
            now,
            &config,
        );
        assert_eq!(health.circuit(), CircuitState::Open { since: now });

        let t1 = now.checked_add(Duration::from_secs(6)).expect("advance");
        assert!(health.try_admit(t1, &config));
        assert_eq!(health.circuit(), CircuitState::HalfOpen { in_flight: true });

        // Failure in HalfOpen re-arms Open { since: t1 }
        health.observe(
            Outcome::Failure {
                class: FailureClass::UpstreamFault,
                was_probe: false,
            },
            t1,
            &config,
        );
        assert_eq!(health.circuit(), CircuitState::Open { since: t1 });
        assert!(!health.is_available(t1, &config));

        let t2 = t1.checked_add(Duration::from_secs(2)).expect("advance");
        assert!(!health.is_available(t2, &config));

        let t3 = t1.checked_add(Duration::from_secs(6)).expect("advance");
        assert!(health.is_available(t3, &config));
    }
}
